/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutStoriesofbizgroImport } from './routes/_layout/storiesofbizgro'
import { Route as LayoutStaffImport } from './routes/_layout/staff'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutQuickFactsImport } from './routes/_layout/quick-facts'
import { Route as LayoutMoneyForYourBizImport } from './routes/_layout/money-for-your-biz'
import { Route as LayoutMissionImport } from './routes/_layout/mission'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutContactImport } from './routes/_layout/contact'
import { Route as LayoutBoardImport } from './routes/_layout/board'
import { Route as LayoutBizgroSkillsImport } from './routes/_layout/bizgro-skills'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutEconomicDevelopmentSitesBuildingsImport } from './routes/_layout/economic-development.sites-buildings'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoriesofbizgroRoute = LayoutStoriesofbizgroImport.update({
  path: '/storiesofbizgro',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStaffRoute = LayoutStaffImport.update({
  path: '/staff',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutQuickFactsRoute = LayoutQuickFactsImport.update({
  path: '/quick-facts',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMoneyForYourBizRoute = LayoutMoneyForYourBizImport.update({
  path: '/money-for-your-biz',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMissionRoute = LayoutMissionImport.update({
  path: '/mission',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutContactRoute = LayoutContactImport.update({
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBoardRoute = LayoutBoardImport.update({
  path: '/board',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBizgroSkillsRoute = LayoutBizgroSkillsImport.update({
  path: '/bizgro-skills',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEconomicDevelopmentSitesBuildingsRoute =
  LayoutEconomicDevelopmentSitesBuildingsImport.update({
    path: '/economic-development/sites-buildings',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/bizgro-skills': {
      preLoaderRoute: typeof LayoutBizgroSkillsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/board': {
      preLoaderRoute: typeof LayoutBoardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/contact': {
      preLoaderRoute: typeof LayoutContactImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/mission': {
      preLoaderRoute: typeof LayoutMissionImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/money-for-your-biz': {
      preLoaderRoute: typeof LayoutMoneyForYourBizImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/quick-facts': {
      preLoaderRoute: typeof LayoutQuickFactsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/staff': {
      preLoaderRoute: typeof LayoutStaffImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/storiesofbizgro': {
      preLoaderRoute: typeof LayoutStoriesofbizgroImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/economic-development/sites-buildings': {
      preLoaderRoute: typeof LayoutEconomicDevelopmentSitesBuildingsImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutBizgroSkillsRoute,
    LayoutBoardRoute,
    LayoutContactRoute,
    LayoutItemsRoute,
    LayoutMissionRoute,
    LayoutMoneyForYourBizRoute,
    LayoutQuickFactsRoute,
    LayoutSettingsRoute,
    LayoutStaffRoute,
    LayoutStoriesofbizgroRoute,
    LayoutIndexRoute,
    LayoutEconomicDevelopmentSitesBuildingsRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
